apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: hanzla119/ecommerce-order:v1 
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP 
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
